### GET - /
GET http://localhost:3000/


### POST - /auth/register
POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "name": "Ava Mitchell",
  "username": "ava_mitchell",
  "email": "ava.mitchell@example.com",
  "password": "Password123"
}


### POST - /auth/login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email": "mia.rodriguez@example.com",
  "password": "Password123"
 }


### GET - /users/me
GET http://localhost:3000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjZhZjRmNmY1YjIxMDA5MzdlYTMzMiIsImlhdCI6MTc2MTYzODM4NywiZXhwIjoxNzYxNzI0Nzg3fQ.w3SvkacWWRJP9etefCLgcNLFrGXG6j3LDClhEeITEGc


### POST - /posts
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjZhZjRmNmY1YjIxMDA5MzdlYTMzMiIsImlhdCI6MTc2NDE0NDc4NiwiZXhwIjoxNzY0MjMxMTg2fQ.tolWE0z-rM3FnWrjGMjFpmJr5apKXUWBAC8B1UT7_LU

{
 "content": "The sunset looked unreal today—like a painting."
}


### GET - /posts
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjZhZjRmNmY1YjIxMDA5MzdlYTMzMiIsImlhdCI6MTc2NDE0NDc4NiwiZXhwIjoxNzY0MjMxMTg2fQ.tolWE0z-rM3FnWrjGMjFpmJr5apKXUWBAC8B1UT7_LU



### GET - /posts/:ID
GET http://localhost:3000/posts/6926b7f916c42e7a73726484
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjZhZjRmNmY1YjIxMDA5MzdlYTMzMiIsImlhdCI6MTc2NDE0NDc4NiwiZXhwIjoxNzY0MjMxMTg2fQ.tolWE0z-rM3FnWrjGMjFpmJr5apKXUWBAC8B1UT7_LU


### PUT - /posts/:ID
PUT http://localhost:3000/posts/6926b7f916c42e7a73726484
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjZhZjRmNmY1YjIxMDA5MzdlYTMzMiIsImlhdCI6MTc2NDE0NDc4NiwiZXhwIjoxNzY0MjMxMTg2fQ.tolWE0z-rM3FnWrjGMjFpmJr5apKXUWBAC8B1UT7_LU

{
 "content": "The sunset looked unreal today—like a painting."
}


### DELETE - /posts/:ID
DELETE http://localhost:3000/posts/6926b7f916c42e7a73726484
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MjZhZjRmNmY1YjIxMDA5MzdlYTMzMiIsImlhdCI6MTc2NDE0NDc4NiwiZXhwIjoxNzY0MjMxMTg2fQ.tolWE0z-rM3FnWrjGMjFpmJr5apKXUWBAC8B1UT7_LU